services:
  - type: web
    name: ai-article-tool
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "node server.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 20
